### ISSUE TITLE
No Area for putting the token and the prefix

### ISSUE THREAD

**Issue by PratikJena-ops** [Hitstar53/StarBot#2]
Where to put the token and the prefix of the bot?

**Comment by Hitstar53** [comment]
For that you need an index.js with a aoi.js setup code which can be found here: https://aoi.leref.ga/  . Keep in mind although the git is public my bot source code is not public now so these are some old codes that i had uploaded before now they have been replaced with newer codes…..

**Comment by PratikJena-ops** [comment]
So when will be the bot's source code public? Waiting for it

**Comment by Hitstar53** [comment]
Not in the nearby future i think as i am properly developing the bot lets see if i stop work on the project in the future i will definitely make the src code public on git :)
